; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:genericSTM32F103C8]
platform = ststm32
board = genericSTM32F103C8
framework = stm32cube
build_flags =
	-IMiddlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2
	-IMiddlewares/Third_Party/FreeRTOS/Source/include
	-IMiddlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3
build_src_filter =
	+<Core/Src/*>
	+<Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2/cmsis_os2.c>
	+<Middlewares/Third_Party/FreeRTOS/Source/list.c>
	+<Middlewares/Third_Party/FreeRTOS/Source/queue.c>
	+<Middlewares/Third_Party/FreeRTOS/Source/tasks.c>
	+<Middlewares/Third_Party/FreeRTOS/Source/timers.c>
	+<Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM3/port.c>
	+<Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c>
[platformio]
src_dir=.
include_dir=Core/Inc

